// Generated by Interoptopus. Include this shared support file once per C# compilation.
#nullable enable
using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Threading;
using System.Threading.Tasks;

namespace Rust.Linq;

/// A query source selected by ToRust. Native sources are owning and single-pass;
/// managed adapters retain their source's normal enumeration behavior.
public interface IRustEnumerable<out T> : IEnumerable<T>, IDisposable
{
    // Provider hooks. Consumers normally use the extension methods below.
    [EditorBrowsable(EditorBrowsableState.Never)]
    IRustEnumerable<T> WhereCore(Func<T, bool> predicate);
    [EditorBrowsable(EditorBrowsableState.Never)]
    IRustEnumerable<T> TakeCore(int count);
    [EditorBrowsable(EditorBrowsableState.Never)]
    bool AnyCore();
}

/// Owns native query state created during one script execution. Keep this scope
/// alive through consumption of lazy or async results. Persistent services remain host-owned.
public sealed class ScriptScope : IDisposable, IAsyncDisposable
{
    private static readonly AsyncLocal<ScriptScope?> Ambient = new();
    private readonly object _gate = new();
    private readonly HashSet<IDisposable> _resources = new(ReferenceEqualityComparer.Instance);
    private readonly ScriptScope? _parent;
    private readonly TaskCompletionSource _cleanup = new(TaskCreationOptions.RunContinuationsAsynchronously);
    private bool _disposed;

    public ScriptScope(CancellationToken cancellationToken = default)
    {
        _parent = Ambient.Value;
        CancellationToken = ResolveCancellation(cancellationToken);
        Ambient.Value = this;
    }

    public CancellationToken CancellationToken { get; }
    public static CancellationToken CurrentCancellationToken => Ambient.Value?.CancellationToken ?? default;
    [EditorBrowsable(EditorBrowsableState.Never)]
    public static ScriptScope? Current => Ambient.Value;
    [EditorBrowsable(EditorBrowsableState.Never)]
    public static CancellationToken ResolveCancellation(CancellationToken token)
        => token.CanBeCanceled ? token : CurrentCancellationToken;

    [EditorBrowsable(EditorBrowsableState.Never)]
    public void Register(IDisposable resource)
    {
        ArgumentNullException.ThrowIfNull(resource);
        lock (_gate)
        {
            if (!_disposed)
            {
                _resources.Add(resource);
                return;
            }
        }
        // A captured execution context cannot create query state after its scope closes.
        resource.Dispose();
        throw new ObjectDisposedException(nameof(ScriptScope));
    }

    [EditorBrowsable(EditorBrowsableState.Never)]
    public void Unregister(IDisposable resource)
    {
        lock (_gate) _resources.Remove(resource);
    }

    public void Dispose()
    {
        // Restore this context even when another captured context already closed the scope.
        if (ReferenceEquals(Ambient.Value, this))
        {
            var parent = _parent;
            while (parent is not null && Volatile.Read(ref parent._disposed)) parent = parent._parent;
            Ambient.Value = parent;
        }
        IDisposable[] resources;
        lock (_gate)
        {
            if (_disposed) return;
            _disposed = true;
            resources = new IDisposable[_resources.Count];
            _resources.CopyTo(resources);
            _resources.Clear();
        }
        List<Exception>? errors = null;
        List<Task>? pending = null;
        foreach (var resource in resources)
        {
            try
            {
                if (resource is IAsyncDisposable asynchronous)
                {
                    var cleanup = asynchronous.DisposeAsync();
                    if (cleanup.IsCompletedSuccessfully) cleanup.GetAwaiter().GetResult();
                    else (pending ??= new()).Add(cleanup.AsTask());
                }
                else resource.Dispose();
            }
            catch (Exception error) { (errors ??= new()).Add(error); }
        }
        var immediateError = errors is null ? null : new AggregateException("Script query cleanup failed.", errors);
        _ = FinishCleanupAsync(pending, errors);
        if (immediateError is not null) throw immediateError;
    }

    /// Cancels pending native stream pulls and waits until Rust has released them.
    public ValueTask DisposeAsync()
    {
        // Restore the ambient scope synchronously in the caller's execution context.
        try { Dispose(); }
        catch (AggregateException) { } // The same errors are retained in _cleanup.
        return new ValueTask(_cleanup.Task);
    }

    private async Task FinishCleanupAsync(List<Task>? pending, List<Exception>? errors)
    {
        if (pending is not null)
        {
            foreach (var task in pending)
            {
                try { await task.ConfigureAwait(false); }
                catch (Exception error) { (errors ??= new()).Add(error); }
            }
        }
        if (errors is null) _cleanup.TrySetResult();
        else _cleanup.TrySetException(new AggregateException("Script query cleanup failed.", errors));
    }
}

/// Query operators for explicitly selected Rust.Linq sources.
public static class RustEnumerable
{
    /// Creates a reusable live view. The bridge must supply a fresh owned traversal
    /// on every call. Creating or composing this view does not invoke the factory.
    public static IRustEnumerable<T> FromFactory<T>(Func<IRustEnumerable<T>> factory)
    {
        ArgumentNullException.ThrowIfNull(factory);
        return new FactoryEnumerable<T>(factory);
    }

    /// Creates a reusable native async view from a fresh-traversal factory.
    public static IAsyncEnumerable<T> FromFactory<T>(Func<IAsyncEnumerable<T>> factory)
    {
        ArgumentNullException.ThrowIfNull(factory);
        return EnumerateFactory(factory);
    }

    private static async IAsyncEnumerable<T> EnumerateFactory<T>(
        Func<IAsyncEnumerable<T>> factory,
        [global::System.Runtime.CompilerServices.EnumeratorCancellation] CancellationToken cancellationToken = default)
    {
        cancellationToken = ScriptScope.ResolveCancellation(cancellationToken);
        cancellationToken.ThrowIfCancellationRequested();
        var source = factory() ?? throw new InvalidOperationException("The async traversal factory returned null.");
        try
        {
            await foreach (var item in source.WithCancellation(cancellationToken).ConfigureAwait(false))
                yield return item;
        }
        finally
        {
            if (source is IAsyncDisposable asynchronous) await asynchronous.DisposeAsync().ConfigureAwait(false);
            else if (source is IDisposable disposable) disposable.Dispose();
        }
    }

    /// Selects this query API without enumerating or copying the source.
    /// Existing Rust sources retain native execution; other sources use managed LINQ.
    public static IRustEnumerable<T> ToRust<T>(this IEnumerable<T> source)
    {
        ArgumentNullException.ThrowIfNull(source);
        return source as IRustEnumerable<T> ?? new ManagedEnumerable<T>(source);
    }

    public static IRustEnumerable<T> Where<T>(this IRustEnumerable<T> source, Func<T, bool> predicate)
    {
        ArgumentNullException.ThrowIfNull(source);
        ArgumentNullException.ThrowIfNull(predicate);
        return source.WhereCore(predicate);
    }

    public static IRustEnumerable<T> Take<T>(this IRustEnumerable<T> source, int count)
    {
        ArgumentNullException.ThrowIfNull(source);
        return source.TakeCore(count);
    }

    public static bool Any<T>(this IRustEnumerable<T> source)
    {
        ArgumentNullException.ThrowIfNull(source);
        return source.AnyCore();
    }

    public static bool Any<T>(this IRustEnumerable<T> source, Func<T, bool> predicate)
    {
        ArgumentNullException.ThrowIfNull(source);
        ArgumentNullException.ThrowIfNull(predicate);
        using var query = source.WhereCore(predicate);
        return query.AnyCore();
    }


    /// Views this source as a standard async sequence. Native traversal stays
    /// synchronous; async predicates await in C# between individual native pulls.
    /// Ownership remains with the source until enumeration starts.
    public static IAsyncEnumerable<T> ToAsyncEnumerable<T>(this IRustEnumerable<T> source)
    {
        ArgumentNullException.ThrowIfNull(source);
        return new AsyncSource<T>(source);
    }

    /// Enables await foreach directly on an IRustEnumerable.
    public static IAsyncEnumerator<T> GetAsyncEnumerator<T>(
        this IRustEnumerable<T> source, CancellationToken cancellationToken = default)
        => source.ToAsyncEnumerable().GetAsyncEnumerator(cancellationToken);

    /// Awaits each predicate in sequence without blocking or buffering the source.
    public static IAsyncEnumerable<T> Where<T>(
        this IRustEnumerable<T> source, Func<T, Task<bool>> predicate)
    {
        ArgumentNullException.ThrowIfNull(source);
        ArgumentNullException.ThrowIfNull(predicate);
        return source.ToAsyncEnumerable().Where(predicate);
    }

    /// The enumeration token is passed to each predicate for cooperative cancellation.
    public static IAsyncEnumerable<T> Where<T>(
        this IRustEnumerable<T> source, Func<T, CancellationToken, ValueTask<bool>> predicate)
    {
        ArgumentNullException.ThrowIfNull(source);
        ArgumentNullException.ThrowIfNull(predicate);
        return global::System.Linq.AsyncEnumerable.Where(source.ToAsyncEnumerable(),
            (item, token) => predicate(item, ScriptScope.ResolveCancellation(token)));
    }

    /// Adapts Task-returning predicates to the framework async LINQ operators.
    /// The cancellation-aware ValueTask overloads are supplied by System.Linq.
    public static IAsyncEnumerable<T> Where<T>(
        this IAsyncEnumerable<T> source, Func<T, Task<bool>> predicate)
    {
        ArgumentNullException.ThrowIfNull(source);
        ArgumentNullException.ThrowIfNull(predicate);
        return global::System.Linq.AsyncEnumerable.Where(
            source, (item, _) => new ValueTask<bool>(predicate(item)));
    }

    public static ValueTask<bool> AnyAsync<T>(
        this IRustEnumerable<T> source, CancellationToken cancellationToken = default)
        => global::System.Linq.AsyncEnumerable.AnyAsync(source.ToAsyncEnumerable(), ScriptScope.ResolveCancellation(cancellationToken));

    public static ValueTask<bool> AnyAsync<T>(
        this IRustEnumerable<T> source, Func<T, bool> predicate,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(source);
        ArgumentNullException.ThrowIfNull(predicate);
        return global::System.Linq.AsyncEnumerable.AnyAsync(
            source.ToAsyncEnumerable(), predicate, ScriptScope.ResolveCancellation(cancellationToken));
    }

    public static ValueTask<bool> AnyAsync<T>(
        this IRustEnumerable<T> source, Func<T, Task<bool>> predicate,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(source);
        ArgumentNullException.ThrowIfNull(predicate);
        return source.ToAsyncEnumerable().AnyAsync(predicate, ScriptScope.ResolveCancellation(cancellationToken));
    }

    public static ValueTask<bool> AnyAsync<T>(
        this IRustEnumerable<T> source, Func<T, CancellationToken, ValueTask<bool>> predicate,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(source);
        ArgumentNullException.ThrowIfNull(predicate);
        return global::System.Linq.AsyncEnumerable.AnyAsync(
            source.ToAsyncEnumerable(), predicate, ScriptScope.ResolveCancellation(cancellationToken));
    }

    public static ValueTask<bool> AnyAsync<T>(
        this IAsyncEnumerable<T> source, Func<T, Task<bool>> predicate,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(source);
        ArgumentNullException.ThrowIfNull(predicate);
        return global::System.Linq.AsyncEnumerable.AnyAsync(
            source, (item, _) => new ValueTask<bool>(predicate(item)), ScriptScope.ResolveCancellation(cancellationToken));
    }


    private sealed class AsyncSource<T> : IAsyncEnumerable<T>
    {
        private readonly IRustEnumerable<T> _source;
        internal AsyncSource(IRustEnumerable<T> source) { _source = source; }

        public IAsyncEnumerator<T> GetAsyncEnumerator(CancellationToken cancellationToken = default)
        {
            cancellationToken = ScriptScope.ResolveCancellation(cancellationToken);
            cancellationToken.ThrowIfCancellationRequested();
            return new AsyncEnumerator<T>(_source.GetEnumerator(), cancellationToken);
        }
    }

    // Each native pull is synchronous and completes inline. Check cancellation
    // before and after the pull; no Task.Run or blocking wait is involved.
    private sealed class AsyncEnumerator<T> : IAsyncEnumerator<T>
    {
        private IEnumerator<T>? _inner;
        private readonly CancellationToken _cancellationToken;

        internal AsyncEnumerator(IEnumerator<T> inner, CancellationToken cancellationToken)
        {
            _inner = inner;
            _cancellationToken = cancellationToken;
        }

        public T Current => (_inner ?? throw new ObjectDisposedException(nameof(AsyncEnumerator<T>))).Current;

        public ValueTask<bool> MoveNextAsync()
        {
            var inner = _inner;
            if (inner is null) return ValueTask.FromResult(false);
            try
            {
                _cancellationToken.ThrowIfCancellationRequested();
                bool hasNext = inner.MoveNext();
                _cancellationToken.ThrowIfCancellationRequested();
                if (!hasNext) DisposeAsync();
                return ValueTask.FromResult(hasNext);
            }
            catch
            {
                DisposeAsync();
                throw;
            }
        }

        public ValueTask DisposeAsync()
        {
            Interlocked.Exchange(ref _inner, null)?.Dispose();
            return ValueTask.CompletedTask;
        }
    }

    private sealed class FactoryEnumerable<T> : IRustEnumerable<T>
    {
        private readonly Func<IRustEnumerable<T>> _factory;
        internal FactoryEnumerable(Func<IRustEnumerable<T>> factory) { _factory = factory; }
        private IRustEnumerable<T> Open()
            => _factory() ?? throw new InvalidOperationException("The traversal factory returned null.");

        public IEnumerator<T> GetEnumerator() => Enumerate().GetEnumerator();

        // Open inside the iterator body: disposing an enumerator before its first
        // MoveNext must not leave an unstarted native traversal behind.
        private IEnumerable<T> Enumerate()
        {
            using var source = Open();
            using var enumerator = source.GetEnumerator();
            while (enumerator.MoveNext()) yield return enumerator.Current;
        }

        IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
        public void Dispose() { } // A view owns no traversal between enumerations.
        IRustEnumerable<T> IRustEnumerable<T>.WhereCore(Func<T, bool> predicate)
        {
            ArgumentNullException.ThrowIfNull(predicate);
            return new FactoryEnumerable<T>(() =>
            {
                var source = Open();
                try { return source.WhereCore(predicate); }
                catch { source.Dispose(); throw; }
            });
        }
        IRustEnumerable<T> IRustEnumerable<T>.TakeCore(int count)
            => new FactoryEnumerable<T>(() =>
            {
                var source = Open();
                try { return source.TakeCore(count); }
                catch { source.Dispose(); throw; }
            });
        bool IRustEnumerable<T>.AnyCore()
        {
            using var source = Open();
            return source.AnyCore();
        }
    }

    private sealed class ManagedEnumerable<T> : IRustEnumerable<T>
    {
        private readonly IEnumerable<T> _source;
        internal ManagedEnumerable(IEnumerable<T> source) { _source = source; }
        public IEnumerator<T> GetEnumerator() => _source.GetEnumerator();
        IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
        // The adapter owns no native state and does not take ownership of its source.
        public void Dispose() { }
        IRustEnumerable<T> IRustEnumerable<T>.WhereCore(Func<T, bool> predicate)
            => new ManagedEnumerable<T>(global::System.Linq.Enumerable.Where(_source, predicate));
        IRustEnumerable<T> IRustEnumerable<T>.TakeCore(int count)
            => new ManagedEnumerable<T>(global::System.Linq.Enumerable.Take(_source, count));
        bool IRustEnumerable<T>.AnyCore() => global::System.Linq.Enumerable.Any(_source);
    }
}
