// Generated by Interoptopus. Include this shared support file once per C# compilation.
#nullable enable
using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;

namespace Rust.Linq;

/// A query source selected by ToRust. Native sources are owning and single-pass;
/// managed adapters retain their source's normal enumeration behavior.
public interface IRustEnumerable<out T> : IEnumerable<T>, IDisposable
{
    // Provider hooks. Consumers normally use the extension methods below.
    [EditorBrowsable(EditorBrowsableState.Never)]
    IRustEnumerable<T> WhereCore(Func<T, bool> predicate);
    [EditorBrowsable(EditorBrowsableState.Never)]
    IRustEnumerable<T> TakeCore(int count);
    [EditorBrowsable(EditorBrowsableState.Never)]
    bool AnyCore();
}

/// Query operators for explicitly selected Rust.Linq sources.
public static class RustEnumerable
{
    /// Selects this query API without enumerating or copying the source.
    /// Existing Rust sources retain native execution; other sources use managed LINQ.
    public static IRustEnumerable<T> ToRust<T>(this IEnumerable<T> source)
    {
        ArgumentNullException.ThrowIfNull(source);
        return source as IRustEnumerable<T> ?? new ManagedEnumerable<T>(source);
    }

    public static IRustEnumerable<T> Where<T>(this IRustEnumerable<T> source, Func<T, bool> predicate)
    {
        ArgumentNullException.ThrowIfNull(source);
        ArgumentNullException.ThrowIfNull(predicate);
        return source.WhereCore(predicate);
    }

    public static IRustEnumerable<T> Take<T>(this IRustEnumerable<T> source, int count)
    {
        ArgumentNullException.ThrowIfNull(source);
        return source.TakeCore(count);
    }

    public static bool Any<T>(this IRustEnumerable<T> source)
    {
        ArgumentNullException.ThrowIfNull(source);
        return source.AnyCore();
    }

    public static bool Any<T>(this IRustEnumerable<T> source, Func<T, bool> predicate)
    {
        ArgumentNullException.ThrowIfNull(source);
        ArgumentNullException.ThrowIfNull(predicate);
        using var query = source.WhereCore(predicate);
        return query.AnyCore();
    }

    private sealed class ManagedEnumerable<T> : IRustEnumerable<T>
    {
        private readonly IEnumerable<T> _source;
        internal ManagedEnumerable(IEnumerable<T> source) { _source = source; }
        public IEnumerator<T> GetEnumerator() => _source.GetEnumerator();
        IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
        // The adapter owns no native state and does not take ownership of its source.
        public void Dispose() { }
        IRustEnumerable<T> IRustEnumerable<T>.WhereCore(Func<T, bool> predicate)
            => new ManagedEnumerable<T>(global::System.Linq.Enumerable.Where(_source, predicate));
        IRustEnumerable<T> IRustEnumerable<T>.TakeCore(int count)
            => new ManagedEnumerable<T>(global::System.Linq.Enumerable.Take(_source, count));
        bool IRustEnumerable<T>.AnyCore() => global::System.Linq.Enumerable.Any(_source);
    }
}
