// Generated by Interoptopus. Include this shared support file once per C# compilation.
#nullable enable
using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Threading;
using System.Threading.Tasks;

namespace Rust.Linq;

/// A query source selected by ToRust. Native sources are owning and single-pass;
/// managed adapters retain their source's normal enumeration behavior.
public interface IRustEnumerable<out T> : IEnumerable<T>, IDisposable
{
    // Provider hooks. Consumers normally use the extension methods below.
    [EditorBrowsable(EditorBrowsableState.Never)]
    IRustEnumerable<T> WhereCore(Func<T, bool> predicate);
    [EditorBrowsable(EditorBrowsableState.Never)]
    IRustEnumerable<T> TakeCore(int count);
    [EditorBrowsable(EditorBrowsableState.Never)]
    bool AnyCore();
}

/// Query operators for explicitly selected Rust.Linq sources.
public static class RustEnumerable
{
    /// Selects this query API without enumerating or copying the source.
    /// Existing Rust sources retain native execution; other sources use managed LINQ.
    public static IRustEnumerable<T> ToRust<T>(this IEnumerable<T> source)
    {
        ArgumentNullException.ThrowIfNull(source);
        return source as IRustEnumerable<T> ?? new ManagedEnumerable<T>(source);
    }

    public static IRustEnumerable<T> Where<T>(this IRustEnumerable<T> source, Func<T, bool> predicate)
    {
        ArgumentNullException.ThrowIfNull(source);
        ArgumentNullException.ThrowIfNull(predicate);
        return source.WhereCore(predicate);
    }

    public static IRustEnumerable<T> Take<T>(this IRustEnumerable<T> source, int count)
    {
        ArgumentNullException.ThrowIfNull(source);
        return source.TakeCore(count);
    }

    public static bool Any<T>(this IRustEnumerable<T> source)
    {
        ArgumentNullException.ThrowIfNull(source);
        return source.AnyCore();
    }

    public static bool Any<T>(this IRustEnumerable<T> source, Func<T, bool> predicate)
    {
        ArgumentNullException.ThrowIfNull(source);
        ArgumentNullException.ThrowIfNull(predicate);
        using var query = source.WhereCore(predicate);
        return query.AnyCore();
    }


    /// Views this source as a standard async sequence. Native traversal stays
    /// synchronous; async predicates await in C# between individual native pulls.
    /// Ownership remains with the source until enumeration starts.
    public static IAsyncEnumerable<T> ToAsyncEnumerable<T>(this IRustEnumerable<T> source)
    {
        ArgumentNullException.ThrowIfNull(source);
        return new AsyncSource<T>(source);
    }

    /// Enables await foreach directly on an IRustEnumerable.
    public static IAsyncEnumerator<T> GetAsyncEnumerator<T>(
        this IRustEnumerable<T> source, CancellationToken cancellationToken = default)
        => source.ToAsyncEnumerable().GetAsyncEnumerator(cancellationToken);

    /// Awaits each predicate in sequence without blocking or buffering the source.
    public static IAsyncEnumerable<T> Where<T>(
        this IRustEnumerable<T> source, Func<T, Task<bool>> predicate)
    {
        ArgumentNullException.ThrowIfNull(source);
        ArgumentNullException.ThrowIfNull(predicate);
        return source.ToAsyncEnumerable().Where(predicate);
    }

    /// The enumeration token is passed to each predicate for cooperative cancellation.
    public static IAsyncEnumerable<T> Where<T>(
        this IRustEnumerable<T> source, Func<T, CancellationToken, ValueTask<bool>> predicate)
    {
        ArgumentNullException.ThrowIfNull(source);
        ArgumentNullException.ThrowIfNull(predicate);
        return global::System.Linq.AsyncEnumerable.Where(source.ToAsyncEnumerable(), predicate);
    }

    /// Adapts Task-returning predicates to the framework async LINQ operators.
    /// The cancellation-aware ValueTask overloads are supplied by System.Linq.
    public static IAsyncEnumerable<T> Where<T>(
        this IAsyncEnumerable<T> source, Func<T, Task<bool>> predicate)
    {
        ArgumentNullException.ThrowIfNull(source);
        ArgumentNullException.ThrowIfNull(predicate);
        return global::System.Linq.AsyncEnumerable.Where(
            source, (item, _) => new ValueTask<bool>(predicate(item)));
    }

    public static ValueTask<bool> AnyAsync<T>(
        this IRustEnumerable<T> source, CancellationToken cancellationToken = default)
        => global::System.Linq.AsyncEnumerable.AnyAsync(source.ToAsyncEnumerable(), cancellationToken);

    public static ValueTask<bool> AnyAsync<T>(
        this IRustEnumerable<T> source, Func<T, bool> predicate,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(source);
        ArgumentNullException.ThrowIfNull(predicate);
        return global::System.Linq.AsyncEnumerable.AnyAsync(
            source.ToAsyncEnumerable(), predicate, cancellationToken);
    }

    public static ValueTask<bool> AnyAsync<T>(
        this IRustEnumerable<T> source, Func<T, Task<bool>> predicate,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(source);
        ArgumentNullException.ThrowIfNull(predicate);
        return source.ToAsyncEnumerable().AnyAsync(predicate, cancellationToken);
    }

    public static ValueTask<bool> AnyAsync<T>(
        this IRustEnumerable<T> source, Func<T, CancellationToken, ValueTask<bool>> predicate,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(source);
        ArgumentNullException.ThrowIfNull(predicate);
        return global::System.Linq.AsyncEnumerable.AnyAsync(
            source.ToAsyncEnumerable(), predicate, cancellationToken);
    }

    public static ValueTask<bool> AnyAsync<T>(
        this IAsyncEnumerable<T> source, Func<T, Task<bool>> predicate,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(source);
        ArgumentNullException.ThrowIfNull(predicate);
        return global::System.Linq.AsyncEnumerable.AnyAsync(
            source, (item, _) => new ValueTask<bool>(predicate(item)), cancellationToken);
    }


    private sealed class AsyncSource<T> : IAsyncEnumerable<T>
    {
        private readonly IRustEnumerable<T> _source;
        internal AsyncSource(IRustEnumerable<T> source) { _source = source; }

        public IAsyncEnumerator<T> GetAsyncEnumerator(CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            return new AsyncEnumerator<T>(_source.GetEnumerator(), cancellationToken);
        }
    }

    // Each native pull is synchronous and completes inline. Check cancellation
    // before and after the pull; no Task.Run or blocking wait is involved.
    private sealed class AsyncEnumerator<T> : IAsyncEnumerator<T>
    {
        private IEnumerator<T>? _inner;
        private readonly CancellationToken _cancellationToken;

        internal AsyncEnumerator(IEnumerator<T> inner, CancellationToken cancellationToken)
        {
            _inner = inner;
            _cancellationToken = cancellationToken;
        }

        public T Current => (_inner ?? throw new ObjectDisposedException(nameof(AsyncEnumerator<T>))).Current;

        public ValueTask<bool> MoveNextAsync()
        {
            var inner = _inner;
            if (inner is null) return ValueTask.FromResult(false);
            try
            {
                _cancellationToken.ThrowIfCancellationRequested();
                bool hasNext = inner.MoveNext();
                _cancellationToken.ThrowIfCancellationRequested();
                if (!hasNext) DisposeAsync();
                return ValueTask.FromResult(hasNext);
            }
            catch
            {
                DisposeAsync();
                throw;
            }
        }

        public ValueTask DisposeAsync()
        {
            Interlocked.Exchange(ref _inner, null)?.Dispose();
            return ValueTask.CompletedTask;
        }
    }

    private sealed class ManagedEnumerable<T> : IRustEnumerable<T>
    {
        private readonly IEnumerable<T> _source;
        internal ManagedEnumerable(IEnumerable<T> source) { _source = source; }
        public IEnumerator<T> GetEnumerator() => _source.GetEnumerator();
        IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
        // The adapter owns no native state and does not take ownership of its source.
        public void Dispose() { }
        IRustEnumerable<T> IRustEnumerable<T>.WhereCore(Func<T, bool> predicate)
            => new ManagedEnumerable<T>(global::System.Linq.Enumerable.Where(_source, predicate));
        IRustEnumerable<T> IRustEnumerable<T>.TakeCore(int count)
            => new ManagedEnumerable<T>(global::System.Linq.Enumerable.Take(_source, count));
        bool IRustEnumerable<T>.AnyCore() => global::System.Linq.Enumerable.Any(_source);
    }
}
