[package]
name = "interoptopus_cpython_mps"
description = "Python ctypes binding generation for Interoptopus"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true
homepage.workspace = true

[lib]
name = "interoptopus_cpython"

[dependencies]
interoptopus.workspace = true

[lints]
workspace = true
